apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-auth
  namespace: sc-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-auth
  template:
    metadata:
      labels:
        app: sc-auth
    spec:
      containers:
      - name: sc-auth
        image: sahalaww/sc-auth:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          failureThreshold: 3
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sc-auth-secret
              key: secret
        - name: CONFIG_ENV
          value: config.ProductionConfig
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: sc-auth-secret
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: sc-auth-secret
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: sc-auth-secret
              key: db-pass
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: sc-auth-secret
              key: db-name
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"