name: Docker Image Build & Publish

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:

  build-publish:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sahalaww/sc-auth:$RELEASE_VERSION
    - name: Login Docker
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Publish
      run: |
        docker push "sahalaww/sc-auth:$RELEASE_VERSION"
        
