name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        cat << EOF > .env
        DB_HOST=${{ secrets.DB_HOST }}
        DB_USER=${{ secrets.DB_USER }}
        DB_PASS=${{ secrets.DB_PASS }}
        DB_NAME=${{ secrets.DB_NAME }}
        DEBUG=${{ secrets.DEBUG }}
        SECRET_KEY=${{ secrets.SECRET_KEY }}
        CONFIG_ENV=${{ secrets.CONFIG_ENV }}
        EOF
    - name: DB preparation
      run: |
        export FLASK_APP=main.py
        flask db init
        flask db migrate
        flask db upgrade
    - name: Test with pytest inside flask
      run: |
        flask run-test
